name: mo_eonet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.34
  - python=3.10.8
  - imageio=2.28.1
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pandas=2.0.1
  - pillow=9.5.0
  - pyembree=0.1.6
  - scikit-image=0.20.0
  - scipy=1.10.0
  - trimesh=3.21.6
  - pykdtree=1.3.7.post0
  # pytorch
  - pytorch=1.13.1
  - tensorboardx=2.5.1
  - torchvision=0.14.1
  # utils
  - pytest=7.3.1
  - tqdm=4.65.0
  - pyyaml=6.0
  - pip:
    - h5py==3.8.0
    - plyfile==0.9
    - torch_scatter==2.1.0
    - pymcubes==0.1.4
    