method: mo_onet
data:
  dataset: Shapes3D
  path: /local/disk1/gg/data/synthetic_room_dataset_mo
  classes: null
  input_type: pointcloud
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: points.npz
  item_file: item_dict.npz
  points_iou_file: points.npz
  multi_files: null
  points_subsample: 1024
  points_unpackbits: True
  pointcloud_file: pointcloud.npz
  pointcloud_n: 256
  pointcloud_target_n: 1024
  pointcloud_noise: 0.05
  voxels_file: 'model.binvox'
  padding: 0.1
model:
  decoder: equi_mlp
  encoder: egnn
  segmenter: pointnet
  e2e: True
  decoder_kwargs: {}
  encoder_kwargs: {}
  multi_gpu: False
  c_dim: 512
training:
  out_dir:  out/default
  batch_size: 64
  sequential_batches: 1
  print_every: 200
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: False
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 4
  n_workers_val: 4
test:
  threshold: 0.5
  eval_mesh: True
  eval_pointcloud: True
  remove_wall: False
generation:
  batch_size: 20000
  multimesh: False
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: True
  generate_pointcloud: True
  generation_dir: generation
  use_sampling: False
  resolution_0: 32
  upsampling_steps: 2
  simplify_nfaces: null
  copy_groundtruth: False
  copy_input: True
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: True
  sliding_window: False # added for crop generation