method: mo_onet
data:
  input_type: pointcloud
  classes: ["rooms_04"] # , "rooms_05", "rooms_06", "rooms_07", "rooms_08"]
  path: /local/disk1/gg/data/synthetic_0405
  pointcloud_n: 1000 # 5000 is probably a reasonable number for real training
  pointcloud_noise: 0.001
  points_subsample: 1024 # 2048
  points_file: points_iou
  item_file: item_dict
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  pointcloud_chamfer_file: pointcloud
  multi_files: 10
  voxels_file: null
model:
  encoder: gconv
  encoder_kwargs:
    hidden_size: 64
  decoder: cbn_decoder      
  decoder_kwargs:
    hidden_size: 64
  segmenter: segmenter
  segmenter_kwargs: {}
  c_dim: 32
training:
  out_dir:  out/default
  batch_size: 32
  learning_rate: 0.0001
  print_every: 200
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: False
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 4
  n_workers_val: 4
test:
  threshold: 0.5
  eval_mesh: True
  eval_pointcloud: True
  remove_wall: False
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
