method: mo_onet
data:
  input_type: pointcloud
  classes: ["rooms_04", "rooms_05", "rooms_06", "rooms_07", "rooms_08"]
  path: data/synthetic_room_dataset_mo
  pointcloud_n: 2000
  pointcloud_noise: 0.001
  points_subsample: 1024
  points_file: points_iou
  item_file: item_dict
  points_iou_file: points_iou
  pointcloud_file: pointcloud
  pointcloud_chamfer_file: pointcloud
  multi_files: 10
  voxels_file: null
model:
  encoder: egnn
  encoder_kwargs: 
    hidden_size: 96
    n_layers: 5
    n_neighbors: 30
    instance_norm: True
    attention: True
  decoder: gconv_decoder      
  decoder_kwargs:
    hidden_size: 128
    n_blocks: 4
    n_neighbors: 30
  segmenter: segmenter
  segmenter_kwargs: {}
  c_dim: 24
training:
  out_dir: out/egnn/
  batch_size: 4
  learning_rate: 0.0005
  print_every: 50
  visualize_every: 2000
  checkpoint_every: 5000
  validate_every: 1000
  backup_every: 100000
  weighted_loss: True
  eval_sample: False
  model_selection_metric: iou
  model_selection_mode: maximize
  n_workers: 4
  n_workers_val: 2
test:
  threshold: 0.5
  eval_mesh: True
  eval_pointcloud: True
  remove_wall: False
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
